# -*- coding: utf-8 -*-
"""Adult_Income_Classification:_End-to-End_ML_Pipeline_with_EDA_Feature_Engineering_&_KNN_(GridSearchCV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRA82Vg_ohtrNrBlDbob0bdBpHYLqDgi

# Adult Income Dataset: End-to-End Classification Pipeline with EDA, Feature Engineering & Machine Learning using KNN with GridSearchCV for Hyperparameter Tuning

# Adult Income Dataset Analysis

## Project Goal

This project explores the Adult Income dataset through:

- Exploratory Data Analysis (EDA)
- Feature Engineering
- Classification Modeling
- Model Evaluation

## Technologies Used

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Scikit-Learn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_wine
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder, RobustScaler, MinMaxScaler, OrdinalEncoder, LabelEncoder, FunctionTransformer
from sklearn.linear_model import LinearRegression,SGDRegressor, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error,r2_score,root_mean_squared_error,mean_absolute_error
from sklearn.metrics import accuracy_score,precision_score,recall_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import ConfusionMatrixDisplay

"""# EDA and Visualization"""

df = pd.read_csv('adult_income.csv')

df

print("=== Dataset Shape ===")
print(df.shape)

print("\n=== Feature & Sample Count ===")
print(f"Total potential features: {df.shape[1]}")
print(f"Total sample data: {df.shape[0]}")

print("\n=== First 10 Rows ===")
print(df.head(10))

print("\n=== Random 10 Rows ===")
print(df.sample(10))

print("\n=== Dataset Info ===")
df.info()

print("\n=== Descriptive Statistics ===")
print(df.describe())

print("\n=== Missing Values ===")
print(df.isnull().sum())

print("\n=== Duplicate Rows ===")
print(df.duplicated().sum())

df.drop_duplicates(inplace=True)
print("Duplicates removed")

print(df['workclass'].unique())
print(df['education'].unique())
print(df['occupation'].unique())
print(df['relationship'].unique())
print(df['race'].unique())
print(df['sex'].unique())
print(df['native-country'].unique())
print(df['marital-status'].unique())

# Text Cleaning of Categorical Variables (Removing Noise and Formatting Issues)

categorical_columns = df.select_dtypes(include=["object"]).columns

for col in categorical_columns:
    df[col] = df[col].str.replace(' ', '')
    df[col] = df[col].str.replace('.', '').str.strip()

print("Text Cleaning of Categorical Variables (Removing Noise and Formatting Issues)")

# Handling Missing Values (Replacing '?' with NaN)

df.replace('?', np.nan, inplace=True)

print("Handling Missing Values (Replacing '?' with NaN)")

print(df['workclass'].unique())
print(df['education'].unique())
print(df['occupation'].unique())
print(df['relationship'].unique())
print(df['race'].unique())
print(df['sex'].unique())
print(df['native-country'].unique())
print(df['marital-status'].unique())

"""## Insights

- The Adult Income dataset contains demographic and employment-related information that can be used to analyze income patterns.
- Initial exploration revealed a mix of numerical and categorical features requiring different preprocessing strategies.
- Duplicate records were detected and removed to improve dataset quality.
- Missing values represented by placeholder symbols were identified and prepared for further treatment.
- Categorical features were standardized through text cleaning to ensure consistency.
- The dataset is well-suited for machine learning tasks after proper preprocessing and feature engineering.
"""

sns.countplot(data=df, x='income')
plt.title("Target Variable Distribution", fontsize=14)
plt.show()

# Education Feature

education_order = ['Preschool','1st-4th','5th-6th','7th-8th','9th','10th','11th','12th','HS-grad','Some-college','Assoc-voc','Assoc-acdm','Bachelors','Masters','Prof-school','Doctorate']

sns.countplot(data=df,x='education',hue='income',order=education_order)

plt.xticks(rotation=90)
plt.title("Education vs Income", fontsize=14)
plt.show()

sns.countplot(
    data=df,
    x='occupation',
    hue='income'
)

plt.xticks(rotation=90)
plt.title("Occupation vs Income", fontsize=14)
plt.show()

sns.countplot(
    data=df,
    x='workclass',
    hue='income'
)

plt.xticks(rotation=90)
plt.title("Workclass vs Income", fontsize=14)
plt.show()

sns.countplot(
    data=df,
    x='marital-status',
    hue='income'
)

plt.xticks(rotation=90)

plt.title("Marital Status vs Income", fontsize=14)
plt.show()

sns.countplot(
    data=df,
    x='relationship',
    hue='income'
)

plt.title("Relationship vs Income", fontsize=14)
plt.xticks(rotation=90)
plt.show()

df.columns

sns.countplot(
    data=df,
    x='sex',
    hue='income'
)

plt.title("Sex vs Income", fontsize=14)
plt.xticks(rotation=45)
plt.show()

top = df['native-country'].value_counts().head(10).index

sns.countplot(
    data=df[df['native-country'].isin(top)],
    x='native-country',
    hue='income'
)

plt.title("Native Country vs Income", fontsize=14)
plt.xticks(rotation=45)
plt.show()

sns.kdeplot(
    data=df,
    x='age',
    hue='income',
    fill=True
)
plt.title("Age Distribution by Income", fontsize=14)

plt.show()

sns.histplot(
    data=df,
    x='age',
    hue='income',
    kde=True
)

plt.title("Age Distribution by Income", fontsize=14)

plt.show()

sns.boxplot(
    data=df,
    x='income',
    y='hours-per-week'
)

plt.title("Hours-per-week vs Income", fontsize=14)

plt.show()

sns.boxplot(
    data=df,
    x='income',
    y='education-num'
)

plt.title("Education-num vs Income", fontsize=14)

plt.show()

sns.boxplot(
    data=df,
    x='income',
    y='capital-gain'
)

plt.title("Capital Gain vs Income", fontsize=14)

plt.show()

sns.boxplot(
    data=df,
    x='income',
    y='capital-loss'
)

plt.title("Capital Gain vs Income", fontsize=14)

plt.show()

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap", fontsize=14)

plt.show()

df.hist(figsize = (12,8), bins = 20)

plt.suptitle("Distribution of Numerical features")
plt.show()

fig, axes = plt.subplots(6, 2, figsize=(15, 15))

sns.kdeplot(df['age'], ax=axes[0,0])
sns.boxplot(df['age'], ax=axes[0,1])

sns.kdeplot(df['fnlwgt'], ax=axes[1,0])
sns.boxplot(df['fnlwgt'], ax=axes[1,1])

sns.kdeplot(df['education-num'], ax=axes[2,0])
sns.boxplot(df['education-num'], ax=axes[2,1])

sns.kdeplot(df['capital-gain'], ax=axes[3,0])
sns.boxplot(df['capital-gain'], ax=axes[3,1])

sns.kdeplot(df['capital-loss'], ax=axes[4,0])
sns.boxplot(df['capital-loss'], ax=axes[4,1])

sns.kdeplot(df['hours-per-week'], ax=axes[5,0])
sns.boxplot(df['hours-per-week'], ax=axes[5,1])

axes[0,0].tick_params(axis='x', rotation=90)
axes[0,1].tick_params(axis='x', rotation=90)
axes[1,0].tick_params(axis='x', rotation=90)
axes[1,1].tick_params(axis='x', rotation=90)
axes[2,0].tick_params(axis='x', rotation=90)
axes[2,1].tick_params(axis='x', rotation=90)
axes[3,0].tick_params(axis='x', rotation=90)
axes[3,1].tick_params(axis='x', rotation=90)
axes[4,0].tick_params(axis='x', rotation=90)
axes[4,1].tick_params(axis='x', rotation=90)
axes[5,0].tick_params(axis='x', rotation=90)
axes[5,1].tick_params(axis='x', rotation=90)

plt.suptitle("Distribution and Outlier Analysis of Numerical Features")
plt.tight_layout()
plt.show()

"""# Feature Engineering & Preprocessing Pipeline Design (Classification)"""

df=pd.read_csv('adult_income.csv')

df.duplicated().sum()

df.drop_duplicates(inplace=True)

categorical_columns = df.select_dtypes(include = ["object"]).columns

for col in categorical_columns:
  df[col] = df[col].str.replace(' ', '')
  df[col] = df[col].str.replace('.', '').str.strip()

df.replace('?', np.nan, inplace=True)

X = df.drop(columns=["income"])
y = df['income']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

imputer_p1 = Pipeline(steps = [
    ('imputer1', SimpleImputer(missing_values=np.nan , strategy='most_frequent')),
    ('encoder',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'))
    ])

imputer_p2 = Pipeline(steps = [
    ('imputer2', SimpleImputer(missing_values=np.nan , strategy='constant',fill_value='Missing',add_indicator=True)),
    ('encoder',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'))
    ])

num_transformer = Pipeline(steps = [('scaler',StandardScaler())])

cat_transformer = Pipeline(steps = [
    ('encoder',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'))])


preprocessor = ColumnTransformer(transformers = [
    ('imputer_1',imputer_p1, ['workclass', 'native-country']),
    ('imputer_2',imputer_p2, ['occupation']),
    ("numerical",num_transformer, ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']),
    ("categorical",cat_transformer,['marital-status',
       'relationship', 'race', 'sex']),
    ])



le = LabelEncoder()

le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

"""Predicting income using Logistic Regression"""

# ---- LogisticRegression ----

lr_model = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model',LogisticRegression(class_weight='balanced',max_iter=1000))
    ]
)

lr_model.fit(X_train,y_train)

y_pred = lr_model.predict(X_test)


print("---Logistic Regression---")
print()

lr_accuracy = accuracy_score(y_test,y_pred)
print(f'Accuracy Score : {lr_accuracy}')
lr_precision = precision_score(y_test,y_pred)
print(f'Precision Score : {lr_precision}')
lr_recall = recall_score(y_test,y_pred)
print(f'Recall Score : {lr_recall}')

"""# Predicting income using KNN with GridSearchCV for Hyperparameter Tuning"""

# ---- knn pipeline ----

knn_model = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('knn',KNeighborsClassifier(n_jobs=-1))
    ]
)
# knn_model.fit(X_train,y_train)

# ---------------------GridSearchCV---------------------

grid = {
    "knn__n_neighbors" : range(221,242, 2),
    "knn__weights" :['uniform','distance'],
    "knn__p" : [1,2]
}


grid_search = GridSearchCV(
    estimator = knn_model,
    param_grid = grid,
    cv = 5,
    n_jobs=-1,
)

grid_search.fit(X_train,y_train)

model = grid_search.best_estimator_

y_pred= model.predict(X_test)

print("---KNN Classifier with GridSearchCV---")
print()
knn_accuracy = accuracy_score(y_test,y_pred)
print(f'Accuracy Score : {knn_accuracy}')
knn_precision = precision_score(y_test,y_pred)
print(f'Precision Score : {knn_precision}')
knn_recall = recall_score(y_test,y_pred)
print(f'Recall Score : {knn_recall}')

classification_compare = pd.DataFrame({
    'Model':     ['Logistic Regression (Default)', 'KNN (Tuned)'],
    'Accuracy':  [round(lr_accuracy,4),  round(knn_accuracy,4)],
    'Precision': [round(lr_precision,4), round(knn_precision,4)],
    'Recall':    [round(lr_recall,4),  round(knn_recall,4)]
})

print(classification_compare.to_string(index=False))

import matplotlib.pyplot as plt

# Metrics to compare
metrics = ['Accuracy', 'Precision', 'Recall']

# Logistic Regression scores
lr_scores = [
    lr_accuracy,
    lr_precision,
    lr_recall
]

# KNN scores
knn_scores = [
    knn_accuracy,
    knn_precision,
    knn_recall
]

# Create comparison DataFrame
comparison_df = pd.DataFrame({
    'Metric': metrics,
    'Logistic Regression': lr_scores,
    'KNN': knn_scores
})

# Plot
ax = comparison_df.set_index('Metric').plot(
    kind='bar',
    figsize=(10,6),
    rot=0
)


plt.title('Classification Model Performance Comparison')
plt.ylabel('Score')
plt.xlabel('Evaluation Metrics')
plt.ylim(0, 1)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.legend(title='Model')

# Add value labels
for container in ax.containers:
    ax.bar_label(container, fmt='%.4f', padding=3)

plt.tight_layout()
plt.show()

"""# Conclusion

## Key Findings

• Education level strongly influences income.

• Capital Gain is one of the strongest predictors.

• Married individuals are more likely to belong to the >50K class.

• Logistic Regression and KNN achieved competitive performance after preprocessing.

# Logistic Regression Cross Validation
"""

# ---------------- Cross Validation (Logistic Regression) ----------------

lr_cv_scores = cross_val_score(
    lr_model,
    X,
    y,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

print("----- Logistic Regression Cross Validation -----")
print()

print("Cross Validation Scores:")
print(lr_cv_scores)

print()

print(f"Mean Accuracy : {lr_cv_scores.mean():.4f}")
print(f"Standard Deviation : {lr_cv_scores.std():.4f}")

"""# KNN (Best Model) Cross Validation"""

# ---------------- Cross Validation (Best KNN Model) ----------------

model = grid_search.best_estimator_

knn_cv_scores = cross_val_score(
    model,
    X,
    y,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

print("----- KNN Cross Validation -----")
print()

print("Cross Validation Scores:")
print(knn_cv_scores)

print()

print(f"Mean Accuracy : {knn_cv_scores.mean():.4f}")
print(f"Standard Deviation : {knn_cv_scores.std():.4f}")

"""# Cross Validation

To evaluate the model's generalization performance, 5-fold Cross Validation was performed.

Cross Validation helps assess how well the model is expected to perform on unseen data by training and validating it across multiple subsets of the dataset.

A low standard deviation indicates consistent performance across different folds, while the mean accuracy provides a more reliable estimate of the model's overall performance.
"""